/* configure printf library for maximal smallness */

#define PRINTF_ALIAS_STANDARD_FUNCTION_NAMES  1
#define PRINTF_SUPPORT_DECIMAL_SPECIFIERS	  0
#define PRINTF_SUPPORT_EXPONENTIAL_SPECIFIERS 0
#define PRINTF_SUPPORT_WRITEBACK_SPECIFIER	  0
#define PRINTF_SUPPORT_LONG_LONG			  0